### ISSUE TITLE
How do I set active state on FlipBarItem when the index is programmatically changed?

### ISSUE THREAD

**Issue by papakay** [deven98/flip_box_bar#2]
I want to commend the great work you did with this package. Please I was wondering if there is a way to change the state of the FlipBarItem when the index is programmatically outside tap event on the FlipBarItem?

Thank you.

**Comment by d3xvn** [comment]
I'll just check and let you know soon.

**Comment by papakay** [comment]
Thanks immensely @deven98

**Comment by d3xvn** [comment]
Extremely sorry for the late reply, been busy with a few things. At the moment it seems there's no way to do it, I'll launch an update soon to fix this.

**Comment by d3xvn** [comment]
I'm also launching another nav bar with a similar structure soon, I'll make sure that doesn't have a similar defect. This may take a little time to fix since people are already using it so I'll have to look at a workaround.

**Comment by papakay** [comment]
Thanks immensely @deven98  for this update. Please do let me know when you launch the new navbar.

**Comment by d3xvn** [comment]
Here's the new BottomNavigationBar: https://github.com/deven98/expanding_bottom_bar 
Now, the programmer sets the selected value not just the initial value, so the earlier problem won't be there. Will migrate this package too.

**Comment by d3xvn** [comment]
@papakay Bug is now fixed in 0.9.2 Please see README and example for programmatically changing index. Thank you for reporting.
