### ISSUE TITLE
Can I specify the backColor of the color of icon and text?

### ISSUE THREAD

**Issue by tdh8316** [deven98/flip_box_bar#3]
Hello, the developer of this great project!

Currently, I cannot change the color of the icon and text when it gets flipped and only can change the background color.

Is there a way to change the color of the icon and text?
If not, it would be great if we can specify both the front and back colors of the icon and text!

**Comment by d3xvn** [comment]
Hi @tdh8316!
I'm not sure I perfectly understand what you're trying to do. 
Would it be possible for you to just leave a code snippet here so that I can either recommend a solution
or make a fix in the package itself?
Thanks!

**Comment by tdh8316** [comment]
Sorry for the vague description and horrible English. 😭 

For instance, the current version of FlipBoxBar can specify backColor like:
```dart
FlipBarItem(
  icon: Icon(Icons.home, color: Colors.black87),
  text: Text("Home", style: TextStyle(color: Colors.black)),
  frontColor: Colors.white,
  backColor: Colors.deepPurpleAccent[100], // backColor!!! (background only)
),
```
As a result, FlipBarItem will replace its frontcolor - Colors.white - with backColor - Colors.deepPurpleAccent[100] - when it `flipped` (or touched?).
But _the color of `text` and `icon` does not be changed._

I want to specify not only backColor (background) but also backColor of icon and text.
like:
```dart
FlipBarItem(
  fronticon: Icon(Icons.home, color: Colors.black87),
  backicon: Icon(Icons.home, color: Colors.white), // added

  fronttext: Text("Home", style: TextStyle(color: Colors.black)),
  backtext: Text("Home", style: TextStyle(color: Colors.white)), // added

  frontColor: Colors.white,
  backColor: Colors.deepPurpleAccent[100], // existing
),
```

best regards!

**Comment by d3xvn** [comment]
My apologies for the delay in addressing the issue. I'm currently overwhelmed with work but I'll see if I can get a solution to this issue by this week.

**Comment by tdh8316** [comment]
This was trouble when I was a newbie of flutter.
Now I know it can implement through a stateful widget.
